version: '3.8'

services:
  scraperv3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: naatv3-scraper
    volumes:
      - ./scraper:/app/scraper
    environment:
      - CORE_API_BASE_URL=http://naat-api:8080
      - SCRAPER_SERVICE_API_KEY=${SCRAPER_SERVICE_API_KEY:?Configura SCRAPER_SERVICE_API_KEY}
    restart: unless-stopped

networks:
  default:
    name: naat_default
    external: true
