version: '3.8'

services:
  scraperv3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: naatv3-scraper
    ports:
      - "8010:8010"
    volumes:
      - ./scraper:/app/scraper
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-naat3:5432/naat_db2
    restart: unless-stopped

networks:
  default:
    name: naat_default
    external: true

